#!/usr/bin/env bash
# Makes the frosted-material lab reachable in the running app by creating five
# one-line route shims under app/lab/. The lab itself lives in lab/ and is inert
# until this is run, so it can be written and reviewed without touching a live
# Metro session.
#
#   bash lab/enable.sh     create the shims (the running app hot-reloads once)
#   bash lab/disable.sh    remove them
#
# Then open the lab on the booted iOS simulator with:
#   xcrun simctl openurl booted 'rndmroll:///lab'
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/app/lab"

if [ -e "$DEST" ] && ! grep -qs "lab/enable.sh" "$DEST/_layout.tsx"; then
  echo "app/lab already exists and was not created by lab/enable.sh; leaving it alone." >&2
  exit 1
fi

mkdir -p "$DEST/entry"

shim() {
  printf '%s\n%s\n' "// Generated by lab/enable.sh. Remove with lab/disable.sh." "$2" > "$DEST/$1"
}

shim '_layout.tsx'   "export { default, unstable_settings } from '@/lab/layout/LabLayout';"
shim 'index.tsx'     "export { default } from '@/lab/screens/LabIndexScreen';"
shim 'feed.tsx'      "export { default } from '@/lab/screens/FeedScreen';"
shim 'diary.tsx'     "export { default } from '@/lab/screens/DiaryScreen';"
shim 'entry/[id].tsx' "export { default } from '@/lab/screens/EntryDetailScreen';"

echo "Lab routes enabled: /lab, /lab/feed, /lab/diary, /lab/entry/[id]"
echo "Open on the booted simulator:  xcrun simctl openurl booted 'rndmroll:///lab'"
